"""Increase regulatory field lengths

Revision ID: 87c2f7142e7a
Revises: 2f1199bfb82d
Create Date: 2026-05-14 14:28:00.888473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c2f7142e7a'
down_revision: Union[str, None] = '2f1199bfb82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_docs_organization_id', table_name='analysis_documents')
    op.create_index(op.f('ix_analysis_documents_organization_id'), 'analysis_documents', ['organization_id'], unique=False)
    op.alter_column('core_actions', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('core_gaps', 'domain',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('core_gaps', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('core_gaps', 'page_reference',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('core_insights', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_simulation_sessions_organization_id', table_name='ha_simulation_sessions')
    op.create_index(op.f('ix_ha_simulation_sessions_organization_id'), 'ha_simulation_sessions', ['organization_id'], unique=False)
    op.drop_index('ix_org_members_org_id', table_name='organization_members')
    op.drop_index('ix_org_members_user_id', table_name='organization_members')
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_unique_constraint('uq_organizations_slug', 'organizations', ['slug'])
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.create_index('ix_org_members_user_id', 'organization_members', ['user_id'], unique=False)
    op.create_index('ix_org_members_org_id', 'organization_members', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_ha_simulation_sessions_organization_id'), table_name='ha_simulation_sessions')
    op.create_index('ix_simulation_sessions_organization_id', 'ha_simulation_sessions', ['organization_id'], unique=False)
    op.alter_column('core_insights', 'category',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('core_gaps', 'page_reference',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('core_gaps', 'severity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('core_gaps', 'domain',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('core_actions', 'priority',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_analysis_documents_organization_id'), table_name='analysis_documents')
    op.create_index('ix_analysis_docs_organization_id', 'analysis_documents', ['organization_id'], unique=False)
    # ### end Alembic commands ###
