"""add_authority_to_analysis_document

Revision ID: bf2e1c5f043b
Revises: e0e646fc2c7d
Create Date: 2026-05-06 19:04:12.279436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2e1c5f043b'
down_revision: Union[str, None] = 'e0e646fc2c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_documents', sa.Column('authority', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_analysis_documents_authority'), 'analysis_documents', ['authority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_documents_authority'), table_name='analysis_documents')
    op.drop_column('analysis_documents', 'authority')
    # ### end Alembic commands ###
