"""add_multi_authority_and_analysis_to_chat

Revision ID: e0e646fc2c7d
Revises: 8c7d39d4c02c
Create Date: 2026-05-04 09:30:22.763465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e646fc2c7d'
down_revision: Union[str, None] = '8c7d39d4c02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('authorities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('active_file_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('is_analysis', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'analysis_data')
    op.drop_column('messages', 'is_analysis')
    op.drop_column('conversations', 'active_file_id')
    op.drop_column('conversations', 'authorities')
    # ### end Alembic commands ###
